version: "2"

services:
  datastore:
    image: singularities/datastore-emulator
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"
    volumes:
      - "./cloud-storage-data:/opt/data:rw"
volumes:
  cloud-storage-data:  
